
// JSDeferred 0.4.0 Copyright (c) 2007 cho45 ( www.lowreal.net )
// // See http://github.com/cho45/jsdeferred
function Deferred(){return this instanceof Deferred?this.init():new Deferred}Deferred.ok=function(a){return a};Deferred.ng=function(a){throw a;};
Deferred.prototype={_id:250149748310446,init:function(){this._next=null;this.callback={ok:Deferred.ok,ng:Deferred.ng};return this},next:function(a){return this._post("ok",a)},error:function(a){return this._post("ng",a)},call:function(a){return this._fire("ok",a)},fail:function(a){return this._fire("ng",a)},cancel:function(){(this.canceller||function(){})();return this.init()},_post:function(a,b){this._next=new Deferred;this._next.callback[a]=b;return this._next},_fire:function(a,b){var c="ok";try{b=
this.callback[a].call(this,b)}catch(d){if(c="ng",b=d,Deferred.onerror)Deferred.onerror(d)}Deferred.isDeferred(b)?b._next=this._next:this._next&&this._next._fire(c,b);return this}};Deferred.isDeferred=function(a){return!!(a&&a._id===Deferred.prototype._id)};Deferred.next_default=function(a){var b=new Deferred,c=setTimeout(function(){b.call()},0);b.canceller=function(){clearTimeout(c)};a&&(b.callback.ok=a);return b};
Deferred.next_faster_way_readystatechange="object"===typeof window&&"http:"==location.protocol&&!window.opera&&/\bMSIE\b/.test(navigator.userAgent)&&function(a){var b=new Deferred,c=(new Date).getTime();if(150>c-arguments.callee._prev_timeout_called){var d=!1,f=document.createElement("script");f.type="text/javascript";f.src="data:text/javascript,";f.onreadystatechange=function(){d||(b.canceller(),b.call())};b.canceller=function(){d||(d=!0,f.onreadystatechange=null,document.body.removeChild(f))};document.body.appendChild(f)}else{arguments.callee._prev_timeout_called=
c;var e=setTimeout(function(){b.call()},0);b.canceller=function(){clearTimeout(e)}}a&&(b.callback.ok=a);return b};
Deferred.next_faster_way_Image="object"===typeof window&&"undefined"!=typeof Image&&!window.opera&&document.addEventListener&&function(a){var b=new Deferred,c=new Image,d=function(){b.canceller();b.call()};c.addEventListener("load",d,!1);c.addEventListener("error",d,!1);b.canceller=function(){c.removeEventListener("load",d,!1);c.removeEventListener("error",d,!1)};c.src="data:image/png,"+Math.random();a&&(b.callback.ok=a);return b};
Deferred.next_tick="object"===typeof process&&"function"===typeof process.nextTick&&function(a){var b=new Deferred;process.nextTick(function(){b.call()});a&&(b.callback.ok=a);return b};Deferred.next=Deferred.next_faster_way_readystatechange||Deferred.next_faster_way_Image||Deferred.next_tick||Deferred.next_default;
Deferred.chain=function(){for(var a=Deferred.next(),b=0,c=arguments.length;b<c;b++)(function(b){switch(typeof b){case "function":var c=null;try{c=b.toString().match(/^\s*function\s+([^\s()]+)/)[1]}catch(e){}a="error"!=c?a.next(b):a.error(b);break;case "object":a=a.next(function(){return Deferred.parallel(b)});break;default:throw"unknown type in process chains";}})(arguments[b]);return a};
Deferred.wait=function(a){var b=new Deferred,c=new Date,d=setTimeout(function(){b.call((new Date).getTime()-c.getTime())},1E3*a);b.canceller=function(){clearTimeout(d)};return b};Deferred.call=function(a){var b=Array.prototype.slice.call(arguments,1);return Deferred.next(function(){return a.apply(this,b)})};
Deferred.parallel=function(a){var b=!1;if(1<arguments.length)a=Array.prototype.slice.call(arguments),b=!0;else if(Array.isArray&&Array.isArray(a)||"number"==typeof a.length)b=!0;var c=new Deferred,d={},f=0,e;for(e in a)a.hasOwnProperty(e)&&function(e,h){"function"==typeof e&&(a[h]=e=Deferred.next(e));e.next(function(e){d[h]=e;0>=--f&&(b&&(d.length=a.length,d=Array.prototype.slice.call(d,0)),c.call(d))}).error(function(a){c.fail(a)});f++}(a[e],e);f||Deferred.next(function(){c.call()});c.canceller=
function(){for(var b in a)a.hasOwnProperty(b)&&a[b].cancel()};return c};
Deferred.earlier=function(a){var b=!1;if(1<arguments.length)a=Array.prototype.slice.call(arguments),b=!0;else if(Array.isArray&&Array.isArray(a)||"number"==typeof a.length)b=!0;var c=new Deferred,d={},f=0,e;for(e in a)a.hasOwnProperty(e)&&function(e,h){e.next(function(e){d[h]=e;b&&(d.length=a.length,d=Array.prototype.slice.call(d,0));c.call(d);c.canceller()}).error(function(a){c.fail(a)});f++}(a[e],e);f||Deferred.next(function(){c.call()});c.canceller=function(){for(var b in a)a.hasOwnProperty(b)&&
a[b].cancel()};return c};Deferred.loop=function(a,b){var c={begin:a.begin||0,end:"number"==typeof a.end?a.end:a-1,step:a.step||1,last:!1,prev:null},d,f=c.step;return Deferred.next(function(){function a(g){return g<=c.end?(g+f>c.end&&(c.last=!0,c.step=c.end-g+1),c.prev=d,d=b.call(this,g,c),Deferred.isDeferred(d)?d.next(function(b){d=b;return Deferred.call(a,g+f)}):Deferred.call(a,g+f)):d}return c.begin<=c.end?Deferred.call(a,c.begin):null})};
Deferred.repeat=function(a,b){var c=0;return Deferred.next(function(){var d=(new Date).getTime();do{if(c>=a)return null;b(c++)}while(20>(new Date).getTime()-d);return Deferred.call(arguments.callee)})};Deferred.register=function(a,b){this.prototype[a]=function(){var a=arguments;return this.next(function(){return b.apply(this,a)})}};Deferred.register("loop",Deferred.loop);Deferred.register("wait",Deferred.wait);
Deferred.connect=function(a,b,c){var d,f;"string"==typeof b?(d=a,f=d[b],a=c||{}):(f=a,a=b||{},d=a.target);var e=a.args?Array.prototype.slice.call(a.args,0):[],g=isFinite(a.ok)?a.ok:a.args?a.args.length:void 0,h=a.ng;return function(){var a=(new Deferred).next(function(a){var b=this._next.callback.ok;this._next.callback.ok=function(){return b.apply(this,a.args)}}),b=e.concat(Array.prototype.slice.call(arguments,0));if(!(isFinite(g)&&g!==null))g=b.length;b.splice(g,0,function(){a.call(new Deferred.Arguments(arguments))});
isFinite(h)&&h!==null&&b.splice(h,0,function(){a.fail(arguments)});Deferred.next(function(){f.apply(d,b)});return a}};Deferred.Arguments=function(a){this.args=Array.prototype.slice.call(a,0)};Deferred.retry=function(a,b,c){c||(c={});var d=c.wait||0,f=new Deferred,e=function(){b(a).next(function(a){f.call(a)}).error(function(b){0>=--a?f.fail(["retry failed",b]):setTimeout(e,1E3*d)})};setTimeout(e,0);return f};Deferred.methods="parallel,wait,next,call,loop,repeat,chain".split(",");
Deferred.define=function(a,b){b||(b=Deferred.methods);a||(a=function(){return this}());for(var c=0;c<b.length;c++){var d=b[c];a[d]=Deferred[d]}return Deferred};this.Deferred=Deferred;
(function(a){function b(a){a.toJSDeferred=function(){return Deferred.absorb(this)};a.next=function(a){return Deferred.absorb(this).next(a)};a.error=function(a){return Deferred.absorb(this).error(a)};a.done(function(b){a._next&&a._next._fire("ok",b)});a.fail(function(b){a._next&&a._next._fire("ok",b)});var c=a.promise;a.promise=function(){return b(c.apply(this,arguments))};return a}Deferred.absorb=function(a){var b=new Deferred;b.progress=function(){};a.done(function(a){a.toJSDeferred&&delete a.toJSDeferred;
b.call(a)});a.fail(function(a){a.toJSDeferred&&delete a.toJSDeferred;b.fail(a)});a.progress&&a.progress(function(a){b.progress(a)});return b};var c=a.Deferred;a.Deferred=function(a){return b(c.apply(this,arguments))};var d=a.ajax;a.ajax=function(){return d.apply(this,arguments)};var f=Deferred.isDeferred;Deferred.isDeferred=function(a){return f(a)||!(!a||!a.toJSDeferred)};a.JSDeferred=Deferred})(jQuery);
